// Edge function: process-report-schedules
// Cron-triggered: reads enabled report_schedules, generates reports, sends via Resend.
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.45.0";
import * as ExcelJS from "https://esm.sh/exceljs@4.4.0";
import { encode as b64encode } from "https://deno.land/std@0.224.0/encoding/base64.ts";

const cors = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type, x-cron-secret",
};

// ── Types ─────────────────────────────────────────────────────────────────

interface ReportSchedule {
  id: string;
  project_id: string;
  report_type: string;
  frequency: "daily" | "weekly" | "monthly" | "quarterly";
  day_of_week: number | null;
  day_of_month: number | null;
  recipients: string[];
  format: "pdf" | "csv" | "xlsx";
  enabled: boolean;
  label: string;
  last_sent_at: string | null;
}

interface ReportOutput {
  csv: string;
  html: string;
  xlsx?: Uint8Array;
}

// ── Due detection ─────────────────────────────────────────────────────────

function isDue(schedule: ReportSchedule): boolean {
  if (!schedule.last_sent_at) return true;

  const now = Date.now();
  const last = new Date(schedule.last_sent_at).getTime();
  const hoursSince = (now - last) / 3_600_000;

  switch (schedule.frequency) {
    case "daily":    return hoursSince >= 24;
    case "weekly":   return hoursSince >= 24 * 7;
    case "monthly":  return hoursSince >= 24 * 28;
    case "quarterly":return hoursSince >= 24 * 90;
  }
}

// ── CSV helpers ───────────────────────────────────────────────────────────

function csvQuote(v: unknown): string {
  if (v === null || v === undefined) return "";
  const s = String(v);
  return s.includes(",") || s.includes('"') || s.includes("\n")
    ? `"${s.replace(/"/g, '""')}"`
    : s;
}

function toCsv(rows: Record<string, unknown>[], columns: { key: string; label: string }[]): string {
  const header = columns.map((c) => csvQuote(c.label)).join(",");
  const data = rows.map((r) => columns.map((c) => csvQuote(r[c.key])).join(","));
  return "\uFEFF" + header + "\n" + data.join("\n") + "\n";
}

// ── HTML email helpers ────────────────────────────────────────────────────

function htmlTable(
  title: string,
  columns: { key: string; label: string }[],
  rows: Record<string, unknown>[],
): string {
  const thead = columns.map((c) => `<th style="padding:8px 12px;text-align:left;background:#1e3a8a;color:#fff;font-weight:600;white-space:nowrap">${c.label}</th>`).join("");
  const tbody = rows.map((r, i) => {
    const bg = i % 2 === 0 ? "#ffffff" : "#f9fafb";
    const cells = columns.map((c) => `<td style="padding:6px 12px;border-bottom:1px solid #e5e7eb">${r[c.key] ?? ""}</td>`).join("");
    return `<tr style="background:${bg}">${cells}</tr>`;
  }).join("");

  return `
<!DOCTYPE html>
<html><head><meta charset="utf-8"></head>
<body style="margin:0;padding:0;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif">
<div style="max-width:800px;margin:0 auto;padding:24px">
  <div style="background:#1e3a8a;padding:16px 24px;border-radius:8px 8px 0 0">
    <h1 style="margin:0;color:#fff;font-size:20px">${title}</h1>
  </div>
  <div style="background:#fff;border:1px solid #e5e7eb;border-top:0;border-radius:0 0 8px 8px;padding:16px;overflow-x:auto">
    <table style="width:100%;border-collapse:collapse;font-size:13px">
      <thead>${thead}</thead>
      <tbody>${tbody}</tbody>
    </table>
  </div>
  <p style="font-size:11px;color:#9ca3af;margin-top:16px;text-align:center">
    Generated by DCOS · ${new Date().toISOString().slice(0, 10)}
  </p>
</div>
</body></html>`.trim();
}

function htmlKpiCards(title: string, kpis: { label: string; value: string }[]): string {
  const cards = kpis.map((k) => `
    <div style="background:#fff;border:1px solid #e5e7eb;border-radius:6px;padding:12px;text-align:center;min-width:120px">
      <div style="font-size:22px;font-weight:700;color:#1e3a8a">${k.value}</div>
      <div style="font-size:11px;color:#6b7280;margin-top:4px">${k.label}</div>
    </div>`).join("");

  return `
<!DOCTYPE html>
<html><head><meta charset="utf-8"></head>
<body style="margin:0;padding:0;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif">
<div style="max-width:600px;margin:0 auto;padding:24px">
  <div style="background:#1e3a8a;padding:16px 24px;border-radius:8px 8px 0 0">
    <h1 style="margin:0;color:#fff;font-size:20px">${title}</h1>
  </div>
  <div style="background:#f3f4f6;border:1px solid #e5e7eb;border-top:0;border-radius:0 0 8px 8px;padding:16px">
    <div style="display:flex;flex-wrap:wrap;gap:12px;justify-content:center">${cards}</div>
  </div>
  <p style="font-size:11px;color:#9ca3af;margin-top:16px;text-align:center">
    Generated by DCOS · ${new Date().toISOString().slice(0, 10)}
  </p>
</div>
</body></html>`.trim();
}

// ── Email sending (Resend) ───────────────────────────────────────────────

async function sendEmail(
  apiKey: string,
  to: string[],
  subject: string,
  html: string,
  attachment?: { filename: string; content: string },
): Promise<void> {
  const payload: Record<string, unknown> = {
    from: "DCOS Reports <reports@dcos.construction>",
    to,
    subject,
    html,
  };
  if (attachment) {
    payload.attachments = [{
      filename: attachment.filename,
      content: attachment.content,
    }];
  }

  const res = await fetch("https://api.resend.com/emails", {
    method: "POST",
    headers: {
      Authorization: `Bearer ${apiKey}`,
      "Content-Type": "application/json",
    },
    body: JSON.stringify(payload),
  });

  if (!res.ok) {
    const body = await res.text();
    throw new Error(`Resend error ${res.status}: ${body}`);
  }
}

// ── Report handlers ───────────────────────────────────────────────────────

async function handleExecutiveDashboard(supabase: any, projectId: string): Promise<ReportOutput> {
  const today = new Date().toISOString().slice(0, 10);

  const [tRes, tsRes, plRes, mRes] = await Promise.all([
    supabase.from("tasks").select("id, status, planned_end, actual_end, project_id").eq("project_id", projectId),
    supabase.from("timesheet_entries").select("user_id, regular_hours, overtime_hours, status").eq("project_id", projectId),
    supabase.from("payroll_lines").select("total_pay, currency"),
    supabase.from("project_members").select("user_id, project_id"),
  ]);

  const tasks = tRes.data ?? [];
  const ts = tsRes.data ?? [];
  const pl = plRes.data ?? [];
  const projMembers = mRes.data ?? [];

  const totalTasks = tasks.length;
  const completed = tasks.filter((t: any) => t.status === "completed" || t.status === "closed").length;
  const inProgress = tasks.filter((t: any) => t.status === "in_progress").length;
  const overdue = tasks.filter((t: any) => t.planned_end && t.planned_end < today && !["completed", "closed", "approved"].includes(t.status)).length;
  const onTime = tasks.filter((t: any) =>
    (t.status === "completed" || t.status === "closed") &&
    t.planned_end && t.actual_end &&
    new Date(t.actual_end) <= new Date(t.planned_end),
  ).length;
  const onTimeRate = completed > 0 ? Math.round((onTime / completed) * 100) : 0;
  const totalHours = ts.reduce((s: number, e: any) => s + Number(e.regular_hours) + Number(e.overtime_hours), 0);
  const payrollTotal = pl.reduce((s: number, l: any) => s + Number(l.total_pay), 0);
  const memberIds = new Set(projMembers.filter((m: any) => m.project_id === projectId).map((m: any) => m.user_id));

  const kpis = [
    { label: "Total Tasks", value: String(totalTasks) },
    { label: "Completed", value: String(completed) },
    { label: "In Progress", value: String(inProgress) },
    { label: "Overdue", value: String(overdue) },
    { label: "On-Time Rate", value: `${onTimeRate}%` },
    { label: "Total Hours", value: String(totalHours) },
    { label: "Payroll", value: `$${payrollTotal.toLocaleString()}` },
    { label: "Members", value: String(memberIds.size) },
  ];

  const csvData = tasks.map((t: any) => ({
    id: t.id, status: t.status, planned_end: t.planned_end ?? "",
    actual_end: t.actual_end ?? "",
  }));
  const csv = toCsv(csvData, [
    { key: "id", label: "Task ID" },
    { key: "status", label: "Status" },
    { key: "planned_end", label: "Planned End" },
    { key: "actual_end", label: "Actual End" },
  ]);
  const html = htmlKpiCards(`Executive Dashboard — ${projectId}`, kpis);

  return { csv, html };
}

async function handleProjectDashboard(supabase: any, projectId: string): Promise<ReportOutput> {
  const today = new Date().toISOString().slice(0, 10);

  const [tRes, costRes, poRes, prRes] = await Promise.all([
    supabase.from("tasks").select("id, status, priority, planned_end, actual_end, progress_pct, category").eq("project_id", projectId),
    supabase.from("project_cost_summaries").select("bac, ac_total, cpi"),
    supabase.from("purchase_orders").select("status, total_amount").eq("project_id", projectId),
    supabase.from("purchase_requisitions").select("status, required_date").eq("project_id", projectId),
  ]);

  const tasks = tRes.data ?? [];
  const costRows = costRes.data ?? [];

  const overallProgress = tasks.length > 0
    ? Math.round(tasks.reduce((s: number, t: any) => s + t.progress_pct, 0) / tasks.length)
    : 0;
  const overdueCount = tasks.filter((t: any) =>
    t.planned_end && t.planned_end < today && !["completed", "closed", "approved"].includes(t.status),
  ).length;
  const criticalTasks = tasks.filter((t: any) =>
    t.planned_end && t.planned_end < today && !["completed", "closed", "approved"].includes(t.status) &&
    (t.priority === "high" || t.priority === "critical"),
  ).length;
  const totalBac = costRows.reduce((s: number, r: any) => s + (r.bac ?? 0), 0);
  const totalAc = costRows.reduce((s: number, r: any) => s + (r.ac_total ?? 0), 0);
  const costVariance = totalBac - totalAc;
  const costVariancePct = totalBac > 0 ? Math.round((costVariance / totalBac) * 100) : 0;
  const completedTasks = tasks.filter((t: any) => t.progress_pct >= 100).length;

  const csvData = tasks.map((t: any) => ({
    id: t.id, status: t.status, priority: t.priority ?? "",
    progress: `${t.progress_pct}%`, planned_end: t.planned_end ?? "",
  }));
  const csv = toCsv(csvData, [
    { key: "id", label: "Task ID" },
    { key: "status", label: "Status" },
    { key: "priority", label: "Priority" },
    { key: "progress", label: "Progress" },
    { key: "planned_end", label: "Planned End" },
  ]);

  const kpis = [
    { label: "Overall Progress", value: `${overallProgress}%` },
    { label: "Completed Tasks", value: String(completedTasks) },
    { label: "Overdue Tasks", value: String(overdueCount) },
    { label: "Critical Tasks", value: String(criticalTasks) },
    { label: "Cost Variance", value: `$${costVariance.toLocaleString()}` },
    { label: "Cost Var %", value: `${costVariancePct}%` },
  ];
  const html = htmlKpiCards(`Project Dashboard — ${projectId}`, kpis);

  return { csv, html };
}

async function handleFinancialReport(supabase: any, projectId: string): Promise<ReportOutput> {
  const [budgetRes, invRes, claimRes, poRes] = await Promise.all([
    supabase.from("project_budgets").select("total_budget, committed_amount, spent_amount").eq("project_id", projectId),
    supabase.from("supplier_invoices").select("status, total_amount, paid_amount, payment_status").eq("project_id", projectId),
    supabase.from("progress_claims").select("total_amount_claimed, total_amount_certified, status").eq("project_id", projectId),
    supabase.from("purchase_orders").select("status, total_amount").eq("project_id", projectId),
  ]);

  const budgets = budgetRes.data ?? [];
  const invoices = invRes.data ?? [];
  const claims = claimRes.data ?? [];

  const totalBudget = budgets.reduce((s: number, b: any) => s + (b.total_budget ?? 0), 0);
  const totalActual = budgets.reduce((s: number, b: any) => s + (b.spent_amount ?? 0), 0);
  const totalCommitted = budgets.reduce((s: number, b: any) => s + (b.committed_amount ?? 0), 0);
  const pendingInvoices = invoices
    .filter((i: any) => i.status !== "paid" && i.status !== "cancelled")
    .reduce((s: number, i: any) => s + (i.total_amount - (i.paid_amount ?? 0)), 0);
  const budgetUtilization = totalBudget > 0 ? Math.round((totalActual / totalBudget) * 100) : 0;

  const rows = invoices.map((i: any) => ({
    status: i.status, total: i.total_amount, paid: i.paid_amount ?? 0,
    payment_status: i.payment_status,
  }));
  const csv = toCsv(rows, [
    { key: "status", label: "Status" },
    { key: "total", label: "Total Amount" },
    { key: "paid", label: "Paid Amount" },
    { key: "payment_status", label: "Payment Status" },
  ]);

  const kpis = [
    { label: "Total Budget", value: `$${totalBudget.toLocaleString()}` },
    { label: "Actual Spend", value: `$${totalActual.toLocaleString()}` },
    { label: "Committed", value: `$${totalCommitted.toLocaleString()}` },
    { label: "Budget Utilization", value: `${budgetUtilization}%` },
    { label: "Pending Invoices", value: `$${pendingInvoices.toLocaleString()}` },
  ];
  const html = htmlKpiCards(`Financial Report — ${projectId}`, kpis);

  return { csv, html };
}

async function handleKpiAlertsSummary(supabase: any, projectId: string): Promise<ReportOutput> {
  const { data, error } = await supabase
    .from("kpi_alert_events")
    .select("*")
    .eq("project_id", projectId)
    .order("created_at", { ascending: false })
    .limit(50);

  if (error) throw error;
  const events = data ?? [];

  const rows = events.map((e: any) => ({
    kpi: e.kpi_name, message: e.message, severity: e.severity ?? "info",
    actual: e.actual_value, threshold: e.threshold_value, created: new Date(e.created_at).toLocaleDateString(),
  }));
  const csv = toCsv(rows, [
    { key: "kpi", label: "KPI" },
    { key: "message", label: "Message" },
    { key: "severity", label: "Severity" },
    { key: "actual", label: "Actual Value" },
    { key: "threshold", label: "Threshold" },
    { key: "created", label: "Date" },
  ]);

  const unreadCount = events.filter((e: any) => !e.read_at).length;
  const criticalCount = events.filter((e: any) => e.severity === "critical").length;

  const html = rows.length > 0
    ? htmlTable("Recent KPI Alerts", [
        { key: "kpi", label: "KPI" },
        { key: "message", label: "Message" },
        { key: "severity", label: "Severity" },
        { key: "actual", label: "Actual" },
        { key: "threshold", label: "Threshold" },
        { key: "created", label: "Date" },
      ], rows)
    : htmlKpiCards("KPI Alerts Summary", [
        { label: "Status", value: "No alerts" },
        { label: "Project", value: projectId },
      ]);

  return {
    csv,
    html,
  };
}

// ── XLSX generation (for xlsx format) ────────────────────────────────────

async function generateXlsx(
  csv: string,
  title: string,
): Promise<Uint8Array> {
  const wb = new ExcelJS.Workbook();
  wb.creator = "DCOS";
  wb.created = new Date();

  const ws = wb.addWorksheet("Report");

  // Title
  ws.mergeCells("A1:Z1");
  const titleCell = ws.getCell("A1");
  titleCell.value = title;
  titleCell.font = { bold: true, size: 14, color: { argb: "FFFFFFFF" } };
  titleCell.fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FF1E3A8A" } };
  titleCell.alignment = { vertical: "middle", horizontal: "left", indent: 1 };
  ws.getRow(1).height = 28;

  // Parse CSV
  const lines = csv.split("\n").filter(Boolean);
  if (lines.length < 2) {
    const buf = await wb.xlsx.writeBuffer();
    return new Uint8Array(buf);
  }

  // Header row
  const headerLine = lines[0].replace(/^[\uFEFF]/, "");
  const parseLine = (line: string): string[] => {
    const result: string[] = [];
    let current = "";
    let inQuotes = false;
    for (let i = 0; i < line.length; i++) {
      const ch = line[i];
      if (ch === '"') {
        if (inQuotes && line[i + 1] === '"') { current += '"'; i++; }
        else inQuotes = !inQuotes;
      } else if (ch === "," && !inQuotes) {
        result.push(current);
        current = "";
      } else {
        current += ch;
      }
    }
    result.push(current);
    return result;
  };

  const headers = parseLine(headerLine);
  const colKeys = headers.map((_, i) => String.fromCharCode(97 + i));

  // Header formatting (row 2)
  const hdrRow = ws.getRow(2);
  headers.forEach((h: string, i: number) => {
    hdrRow.getCell(i + 1).value = h;
  });
  hdrRow.font = { bold: true, color: { argb: "FFFFFFFF" } };
  hdrRow.fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FF374151" } };
  hdrRow.alignment = { vertical: "middle", horizontal: "center" };
  hdrRow.height = 22;

  // Data rows
  for (let r = 1; r < lines.length - 1; r++) {
    const vals = parseLine(lines[r]);
    const row = ws.getRow(r + 2);
    vals.forEach((v: string, i: number) => {
      const num = Number(v);
      row.getCell(i + 1).value = isNaN(num) || v.trim() === "" ? v : num;
    });
  }

  // Auto-width
  headers.forEach((_: string, i: number) => {
    ws.getColumn(i + 1).width = 18;
  });

  ws.views = [{ state: "frozen", ySplit: 2 }];
  const buf = await wb.xlsx.writeBuffer();
  return new Uint8Array(buf);
}

// ── Report type dispatch ──────────────────────────────────────────────────

const HANDLERS: Record<string, (supabase: any, projectId: string) => Promise<ReportOutput>> = {
  executive_dashboard: handleExecutiveDashboard,
  project_dashboard: handleProjectDashboard,
  financial_report: handleFinancialReport,
  kpi_alerts: handleKpiAlertsSummary,
};

// ── Main handler ──────────────────────────────────────────────────────────

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") return new Response(null, { headers: cors });

  // Auth via cron secret header
  const secret = Deno.env.get("CRON_SECRET");
  if (secret && req.headers.get("x-cron-secret") !== secret) {
    return new Response(JSON.stringify({ error: "Unauthorized" }), {
      status: 401,
      headers: { ...cors, "content-type": "application/json" },
    });
  }

  try {
    const supabase = createClient(
      Deno.env.get("SUPABASE_URL")!,
      Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,
    );
    const resendKey = Deno.env.get("RESEND_API_KEY");
    if (!resendKey) {
      return new Response(JSON.stringify({ error: "RESEND_API_KEY not set" }), {
        status: 500,
        headers: { ...cors, "content-type": "application/json" },
      });
    }

    // Fetch all enabled schedules
    const { data: schedules, error: schedErr } = await supabase
      .from("report_schedules")
      .select("*")
      .eq("enabled", true);

    if (schedErr) throw schedErr;
    const enabled: ReportSchedule[] = schedules ?? [];

    // Filter to due schedules
    const due = enabled.filter(isDue);

    if (due.length === 0) {
      return new Response(JSON.stringify({ processed: 0, message: "No due schedules" }), {
        headers: { ...cors, "content-type": "application/json" },
      });
    }

    const results: Record<string, unknown>[] = [];
    for (const schedule of due) {
      results.push(await processOne(supabase, resendKey, schedule));
    }

    const sent = results.filter((r) => r.status === "sent").length;
    const failed = results.filter((r) => r.status === "error").length;

    return new Response(JSON.stringify({
      processed: due.length,
      sent,
      failed,
      results,
    }), {
      headers: { ...cors, "content-type": "application/json" },
    });
  } catch (err) {
    console.error("process-report-schedules error", err);
    return new Response(JSON.stringify({ error: err instanceof Error ? err.message : String(err) }), {
      status: 500,
      headers: { ...cors, "content-type": "application/json" },
    });
  }
});

async function processOne(
  supabase: any,
  resendKey: string,
  schedule: ReportSchedule,
): Promise<Record<string, unknown>> {
  try {
    const handler = HANDLERS[schedule.report_type];
    if (!handler) {
      return { id: schedule.id, label: schedule.label, status: "error", error: `Unknown report_type: ${schedule.report_type}` };
    }

    const report = await handler(supabase, schedule.project_id);
    const now = new Date();
    const dateStr = now.toISOString().slice(0, 10);
    const safeLabel = schedule.label.replace(/[^a-zA-Z0-9_-]/g, "_");

    let subject = `[DCOS Report] ${schedule.label} — ${dateStr}`;
    let htmlBody = report.html;
    let attachment: { filename: string; content: string } | undefined;

    if (schedule.format === "csv") {
      attachment = { filename: `${safeLabel}_${dateStr}.csv`, content: btoa(report.csv) };
    } else if (schedule.format === "xlsx") {
      const xlsxBytes = await generateXlsx(report.csv, schedule.label);
      attachment = { filename: `${safeLabel}_${dateStr}.xlsx`, content: b64encode(xlsxBytes) };
    }
    // For "pdf" format, send as HTML email (no attachment)

    await sendEmail(resendKey, schedule.recipients, subject, htmlBody, attachment);

    // Update last_sent_at
    await supabase
      .from("report_schedules")
      .update({ last_sent_at: now.toISOString(), updated_at: now.toISOString() })
      .eq("id", schedule.id);

    return { id: schedule.id, label: schedule.label, project_id: schedule.project_id, format: schedule.format, status: "sent" };
  } catch (err) {
    console.error(`Failed to process schedule ${schedule.id}`, err);
    return { id: schedule.id, label: schedule.label, status: "error", error: err instanceof Error ? err.message : String(err) };
  }
}
