// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xgfgtsxjzfbalzqgosrn.supabase.co";
const SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhnZmd0c3hqemZiYWx6cWdvc3JuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzkyNjI5MTksImV4cCI6MjA5NDgzODkxOX0.Eeh9qCQOkw15G4SPsGRLcHokcvZGGD3xq6U50WywGb0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_ANON_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
